export interface CatalogProduct {
  id: string
  slug: string
  name: string
  price: number
  originalPrice: number
  category: string
  categoryLabel: string
  badge: 'Bestseller' | 'New' | 'Premium' | 'Sale' | null
  rating: number
  reviews: number
  image: string
  additionalImages?: string[]
  inStock: boolean
  isNew: boolean
  isSale: boolean
  shortDescription: string
  description: string
  highlights: string[]
  fabric: string
  craft: string
  care: string
  sizes: string[]
  sku: string
}

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  // ─── SAREES ─────────────────────────────────────────────────────────────
  {
    id: '1',
    slug: 'banarasi-silk-saree',
    name: 'Banarasi Silk Saree',
    price: 4999,
    originalPrice: 7500,
    category: 'sarees',
    categoryLabel: 'Sarees',
    badge: 'Bestseller',
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=85&auto=format&fit=crop',
    ],
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Exquisite handwoven Banarasi pure silk saree adorned with intricate floral gold zari jaal across the body and a regal pallu.',
    description: 'Immerse yourself in centuries-old heritage with our signature Banarasi Silk Saree. Handcrafted by master weavers in Varanasi, this heirloom saree features opulent antique gold zari motifs delicately woven into pure mulberry silk. Perfect for weddings, grand festivities, and traditional ceremonies.',
    highlights: [
      'Authentic Banarasi Handloom with Silk Mark Certification',
      'Intricate Kadwa gold zari floral work on rich maroon-red body',
      'Comes with matching unstitched pure silk blouse piece (80 cm)',
      'Saree Length: 5.5 meters | Blouse: 0.8 meter',
    ],
    fabric: '100% Pure Mulberry Silk with metallic zari',
    craft: 'Traditional Varanasi Kadwa Handloom Weaving',
    care: 'Dry clean only. Store draped in a breathable muslin cloth away from direct sunlight.',
    sizes: ['Free Size (5.5m + 0.8m Blouse)'],
    sku: 'AAR-SAR-001',
  },
  {
    id: '5',
    slug: 'kanjeevaram-pure-silk-saree',
    name: 'Kanjeevaram Pure Silk Saree',
    price: 8999,
    originalPrice: 12000,
    category: 'sarees',
    categoryLabel: 'Sarees',
    badge: 'New',
    rating: 4.9,
    reviews: 68,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85&auto=format&fit=crop',
    ],
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Regal Kanchipuram silk saree with contrast temple border and heavy brocade pallu in auspicious temple gold.',
    description: 'Woven with three-ply silk yarn and pure silver dipped gold zari, this Kanjeevaram masterpiece represents the pinnacle of South Indian bridal artistry. Its interlocked korvai weaving technique creates crisp color contrasts that radiate elegance.',
    highlights: [
      'Authentic Korvai weaving technique from Kanchipuram artisans',
      'Pure silver-gilt zari with rich temple gopuram motifs',
      'Includes contrast rich brocade blouse fabric',
      'Heirloom quality designed to last for generations',
    ],
    fabric: 'Heavyweight Kanchipuram Pure Silk (3-ply)',
    craft: 'Interlocked Korvai Handloom Weave',
    care: 'Dry clean only. Do not bleach or spray perfume directly on zari.',
    sizes: ['Free Size (5.5m + 0.8m Blouse)'],
    sku: 'AAR-SAR-005',
  },
  {
    id: '9',
    slug: 'chanderi-handloom-silk-saree',
    name: 'Chanderi Handloom Silk Saree',
    price: 3499,
    originalPrice: 4500,
    category: 'sarees',
    categoryLabel: 'Sarees',
    badge: null,
    rating: 4.5,
    reviews: 55,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Lightweight sheer Chanderi silk cotton saree with fine golden booties and delicate zari border.',
    description: 'A breath of fresh air for day festivities and cocktail celebrations. Woven in Madhya Pradesh, this gossamer-light saree features miniature peacock zari booties and a sheer, airy drape.',
    highlights: [
      'Ultra-lightweight feather drape for effortless all-day comfort',
      'Intricate Chanderi gold booties with zari border',
      'Unstitched matching blouse piece included',
    ],
    fabric: 'Chanderi Silk Cotton Blend',
    craft: 'Madhya Pradesh Handloom Weave',
    care: 'Dry clean only. Iron on reverse at moderate temperature.',
    sizes: ['Free Size (5.5m + 0.8m Blouse)'],
    sku: 'AAR-SAR-009',
  },
  {
    id: '13',
    slug: 'georgette-embroidered-saree',
    name: 'Georgette Embroidered Saree',
    price: 2799,
    originalPrice: 3999,
    category: 'sarees',
    categoryLabel: 'Sarees',
    badge: 'Sale',
    rating: 4.6,
    reviews: 42,
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Flowing pure georgette saree featuring intricate threadwork, sequin highlights, and scalloped hem.',
    description: 'Designed for modern celebrations, this pastel georgette saree offers graceful movement and subtle sparkle with tone-on-tone embroidery and micro-sequins.',
    highlights: [
      'Fluid, body-hugging georgette drape',
      'Delicate micro-sequin and thread embroidery',
      'Designer embroidered blouse piece included',
    ],
    fabric: 'Premium Viscose Georgette',
    craft: 'Intricate Machine Threadwork & Hand Embellishment',
    care: 'Dry clean recommended.',
    sizes: ['Free Size (5.5m + 0.8m Blouse)'],
    sku: 'AAR-SAR-013',
  },

  // ─── KURTIS ─────────────────────────────────────────────────────────────
  {
    id: '2',
    slug: 'anarkali-festive-kurti-set',
    name: 'Anarkali Festive Kurti Set',
    price: 1899,
    originalPrice: 2999,
    category: 'kurtis',
    categoryLabel: 'Kurtis',
    badge: 'New',
    rating: 4.6,
    reviews: 87,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&q=85&auto=format&fit=crop',
    ],
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Floor-length flared Anarkali kurti with matching churidar pants and a sheer embroidered dupatta.',
    description: 'Channel royal elegance with this 3-piece Anarkali ensemble. Crafted with deep jewel tones, intricate gota patti neckline work, and a sweeping flare of over 4 meters, it turns every festive gathering into a runway.',
    highlights: [
      '3-Piece Set: Flared Anarkali Kurta, Churidar Pants, Organza Dupatta',
      'Rich Gota Patti hand-embroidery around neckline and cuffs',
      'Soft cotton lining throughout kurta for supreme breathability',
    ],
    fabric: 'Chanderi Rayon Blend with Pure Cotton Inner Lining',
    craft: 'Jaipuri Gota Patti & Hand Embellishment',
    care: 'Hand wash gently in cold water or dry clean.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sku: 'AAR-KUR-002',
  },
  {
    id: '4',
    slug: 'chanderi-silk-floral-kurti',
    name: 'Chanderi Silk Floral Kurti',
    price: 1499,
    originalPrice: 2200,
    category: 'kurtis',
    categoryLabel: 'Kurtis',
    badge: 'Sale',
    rating: 4.5,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Straight-cut Chanderi silk kurti adorned with digital floral motifs and subtle mirrorwork accents.',
    description: 'A versatile staple for festive dinners and semi-formal wear. Straight silhouette featuring delicate potli button details and hand-stitched mirror accents on the yoke.',
    highlights: [
      'Flattering straight cut with side slits',
      'Subtle metallic foil print and real mirror accents',
      'Pre-shrunk fabric ensures consistent fit after washing',
    ],
    fabric: 'Chanderi Silk Blend',
    craft: 'Foil Printing & Mirrorwork',
    care: 'Dry clean or gentle hand wash.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sku: 'AAR-KUR-004',
  },
  {
    id: '7',
    slug: 'cotton-hand-block-printed-kurti',
    name: 'Cotton Hand-Block Printed Kurti',
    price: 799,
    originalPrice: 1200,
    category: 'kurtis',
    categoryLabel: 'Kurtis',
    badge: 'Sale',
    rating: 4.3,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Pure Sanganeri hand block printed cotton kurti designed for daily comfort and breathable elegance.',
    description: 'Made from 100% fine organic cotton and stamped by hand using natural vegetable dyes in Bagru, Rajasthan. Cool, airy, and effortlessly stylish.',
    highlights: [
      '100% Organic Breathable Cotton',
      'Authentic Bagru hand block print using natural dyes',
      'Mandarin collar with functional wooden buttons',
    ],
    fabric: '100% Organic Hand-Block Cotton',
    craft: 'Sanganeri Hand Block Printing',
    care: 'Machine wash cold on gentle cycle. Wash dark colors separately.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    sku: 'AAR-KUR-007',
  },
  {
    id: '10',
    slug: 'flared-palazzo-kurti-ensemble',
    name: 'Flared Palazzo Kurti Ensemble',
    price: 2199,
    originalPrice: 3200,
    category: 'kurtis',
    categoryLabel: 'Kurtis',
    badge: 'New',
    rating: 4.4,
    reviews: 77,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Contemporary tiered flared kurti paired with wide-leg palazzo pants and contrasting printed border.',
    description: 'Combining ethnic sensibility with modern flair, this tiered ensemble gives a dynamic silhouette with fluid movement and comfort.',
    highlights: [
      'Includes A-line kurta and elasticated wide palazzo',
      'Zari lace detailing on sleeve cuffs and hemlines',
      'Side pockets on palazzo pants for daily convenience',
    ],
    fabric: 'Mulmul Cotton Silk',
    craft: 'Tiered Tailoring & Zari Lace Trims',
    care: 'Gentle hand wash in cold water.',
    sizes: ['S', 'M', 'L', 'XL'],
    sku: 'AAR-KUR-010',
  },

  // ─── LEHENGAS ─────────────────────────────────────────────────────────────
  {
    id: '3',
    slug: 'bridal-velvet-lehenga-choli',
    name: 'Bridal Velvet Lehenga Choli',
    price: 12999,
    originalPrice: 18000,
    category: 'lehengas',
    categoryLabel: 'Lehengas',
    badge: 'Premium',
    rating: 4.9,
    reviews: 56,
    image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900&q=85&auto=format&fit=crop',
    additionalImages: [
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900&q=85&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=85&auto=format&fit=crop',
    ],
    inStock: true,
    isNew: false,
    isSale: false,
    shortDescription: 'Opulent crimson bridal micro-velvet lehenga enriched with heavy zardozi, dori work, and double can-can flare.',
    description: 'Crafted for the bride on her most memorable day. This royal ensemble features an intricately embroidered velvet skirt with 5-meter flare, heavily embellished padded choli, and dual net and velvet dupattas.',
    highlights: [
      'Complete 4-Piece Bridal Set: Skirt, Blouse, Bridal Dupatta, Shrug Dupatta',
      'Heavy Zardozi, Cutdana, and Dori hand-embroidery',
      'Double layered can-can and canvas lining for a fairytale flare',
      'Semi-stitched skirt (fits up to 44" waist), unstitched blouse (up to 42" bust)',
    ],
    fabric: 'Royal Micro Velvet with Soft Santoon Inner and Net Dupatta',
    craft: 'Hand Zardozi, Cutdana & Sequin Embroidery',
    care: 'Specialist bridal dry clean only. Store wrapped in pure cotton cloth.',
    sizes: ['Semi-Stitched (Fits XS to XXL)'],
    sku: 'AAR-LEH-003',
  },
  {
    id: '6',
    slug: 'party-wear-semi-stitched-lehenga',
    name: 'Party Wear Semi-Stitched Lehenga',
    price: 5999,
    originalPrice: 8500,
    category: 'lehengas',
    categoryLabel: 'Lehengas',
    badge: 'Sale',
    rating: 4.4,
    reviews: 41,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Pastel festive georgette lehenga featuring sequin floral embroidery and a lightweight ruffled dupatta.',
    description: 'Ideal for sangeet nights, bridesmaids, and reception parties. Lightweight and comfortable to dance the night away without compromising on sparkle.',
    highlights: [
      'Includes semi-stitched skirt, unstitched blouse piece, and net dupatta',
      'Shimmering multi-color sequin and resham threadwork',
      'Lightweight built-in can-can structure',
    ],
    fabric: 'Georgette with Satin Lining and Soft Net Dupatta',
    craft: 'Resham Threadwork & Micro-Sequin Embroidery',
    care: 'Dry clean only.',
    sizes: ['Semi-Stitched (Fits S to XL)'],
    sku: 'AAR-LEH-006',
  },
  {
    id: '14',
    slug: 'silk-brocade-festive-lehenga',
    name: 'Silk Brocade Festive Lehenga',
    price: 9499,
    originalPrice: 13500,
    category: 'lehengas',
    categoryLabel: 'Lehengas',
    badge: 'New',
    rating: 4.8,
    reviews: 38,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Rich Banarasi brocade silk lehenga woven with gold zari flora and a tailored sweetheart blouse.',
    description: 'A tribute to timeless handwoven textiles. Crafted in pure brocade silk with antique gold weaving, this piece exudes understated regal charm.',
    highlights: [
      'Woven Banarasi brocade skirt with 4.5m flare',
      'Sweetheart neckline blouse with back dori ties',
      'Rich contrast tissue organza dupatta with hand-tasselled borders',
    ],
    fabric: 'Banarasi Brocade Silk & Tissue Organza',
    craft: 'Banarasi Handloom Weaving',
    care: 'Dry clean only.',
    sizes: ['Semi-Stitched (Customizable S to XXL)'],
    sku: 'AAR-LEH-014',
  },

  // ─── JEWELLERY & ACCESSORIES ─────────────────────────────────────────────
  {
    id: '11',
    slug: 'antique-temple-gold-jhumkas',
    name: 'Antique Temple Gold Jhumkas',
    price: 899,
    originalPrice: 1200,
    category: 'accessories',
    categoryLabel: 'Jewellery',
    badge: 'Bestseller',
    rating: 4.7,
    reviews: 143,
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: false,
    shortDescription: 'Traditional South Indian antique matte gold finish temple jhumkas adorned with ruby beads and pearl drops.',
    description: 'Handcrafted with intricate Goddess Lakshmi and peacock embossing in matte antique gold plating. Finished with clusters of seed pearls and ruby-red stones.',
    highlights: [
      '22K Matte Gold micro-plated brass alloy',
      'Lead-free, nickel-free, and hypoallergenic posts',
      'Secure push-back closure with silicone comfort backing',
    ],
    fabric: 'High-grade Brass Alloy with Matte Gold Micro-plating',
    craft: 'South Indian Temple Jewellery Craftsmanship',
    care: 'Wipe with soft cloth after use. Store in airtight pouch away from water and perfume.',
    sizes: ['One Size (Length: 5.5 cm)'],
    sku: 'AAR-ACC-011',
  },
  {
    id: '15',
    slug: 'kundan-choker-earring-set',
    name: 'Kundan Choker & Earring Set',
    price: 1899,
    originalPrice: 2600,
    category: 'accessories',
    categoryLabel: 'Jewellery',
    badge: 'Premium',
    rating: 4.9,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Regal Jadau Kundan choker necklace with matching drop earrings and emerald green bead accents.',
    description: 'Turn heads with this handcrafted Rajasthani Kundan choker set. Features meenakari enamel work on the reverse and adjustable golden dori for a customized fit.',
    highlights: [
      'Complete set: Choker Necklace + Matching Drop Earrings',
      'Faceted glass kundan stones with green bead drops',
      'Traditional hand-painted Meenakari enamel on back',
    ],
    fabric: 'Brass Alloy with Hand-Set Jadau Kundan and Hydro Beads',
    craft: 'Rajasthani Kundan & Meenakari Enamelling',
    care: 'Store in velvet-lined box. Keep away from chemicals and moisture.',
    sizes: ['Adjustable Dori Fit (All Neck Sizes)'],
    sku: 'AAR-ACC-015',
  },

  // ─── DUPATTAS ─────────────────────────────────────────────────────────────
  {
    id: '8',
    slug: 'phulkari-embroidered-silk-dupatta',
    name: 'Phulkari Embroidered Silk Dupatta',
    price: 699,
    originalPrice: 999,
    category: 'dupattas',
    categoryLabel: 'Dupattas',
    badge: 'New',
    rating: 4.6,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Vibrant Punjabi Phulkari silk dupatta hand-embroidered with dense floral resham needlework and mirror accents.',
    description: 'An iconic symbol of Punjab’s rich folk textile tradition. Heavy resham geometric patterns on pure chinon silk with mirrorwork highlights.',
    highlights: [
      'Authentic hand-embroidered Phulkari by women artisans of Punjab',
      'Length: 2.4 meters | Width: 38 inches',
      'Gota patti border along all four sides',
    ],
    fabric: 'Chinon Silk with Resham Threadwork',
    craft: 'Authentic Punjabi Phulkari Needlework',
    care: 'Dry clean only.',
    sizes: ['Free Size (2.4m x 1m)'],
    sku: 'AAR-DUP-008',
  },
  {
    id: '16',
    slug: 'bandhani-zari-border-dupatta',
    name: 'Bandhani Zari Border Dupatta',
    price: 849,
    originalPrice: 1199,
    category: 'dupattas',
    categoryLabel: 'Dupattas',
    badge: 'Sale',
    rating: 4.5,
    reviews: 62,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: 'Traditional Gujarati tie-dye Bandhani dupatta on art silk with woven gold zari borders and tassels.',
    description: 'Bright and festive tie-and-dye craft from Kutch. Every tiny dot is tied by hand with thread before dyeing to create intricate bandhej patterns.',
    highlights: [
      'Hand-tied Bandhej dots with golden zari border',
      'Finished with handmade pom-poms and tassels',
      'Generous 2.5m length for regal draping',
    ],
    fabric: 'Art Silk with Woven Gold Zari',
    craft: 'Kutch Hand Tie-and-Dye (Bandhani)',
    care: 'Dry clean recommended.',
    sizes: ['Free Size (2.5m x 1m)'],
    sku: 'AAR-DUP-016',
  },

  // ─── SALWAR SETS ─────────────────────────────────────────────────────────
  {
    id: '12',
    slug: 'bandhani-silk-salwar-suit-set',
    name: 'Bandhani Silk Salwar Suit Set',
    price: 1699,
    originalPrice: 2500,
    category: 'salwar-sets',
    categoryLabel: 'Salwar Sets',
    badge: 'Sale',
    rating: 4.2,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: false,
    isSale: true,
    shortDescription: '3-Piece unstitched Bandhani silk salwar suit with woven zari neck patch and jacquard dupatta.',
    description: 'An evergreen ethnic suit set suitable for all festive and pooja occasions. Includes fabric for kameez, salwar/churidar, and dupatta.',
    highlights: [
      'Unstitched 3-Piece Material: Top (2.5m), Bottom (2.5m), Dupatta (2.25m)',
      'Rich woven Banarasi jacquard neckline',
      'Can be tailored into Straight Suit, Patiala, or Palazzo style',
    ],
    fabric: 'Bandhani Art Silk Top & Bottom with Jacquard Dupatta',
    craft: 'Bandhani Print & Jacquard Weaving',
    care: 'Dry clean for first wash, gentle hand wash thereafter.',
    sizes: ['Unstitched Fabric Set (Up to 48" Bust)'],
    sku: 'AAR-SAL-012',
  },
  {
    id: '17',
    slug: 'chanderi-straight-salwar-suit',
    name: 'Chanderi Straight Salwar Suit',
    price: 2499,
    originalPrice: 3499,
    category: 'salwar-sets',
    categoryLabel: 'Salwar Sets',
    badge: 'New',
    rating: 4.7,
    reviews: 51,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85&auto=format&fit=crop',
    inStock: true,
    isNew: true,
    isSale: false,
    shortDescription: 'Ready-to-wear straight Chanderi suit with delicate thread embroidery, cigarette pants, and organza dupatta.',
    description: 'Crisp tailored silhouette with side slits and pearl button detailing. Paired with ankle-length cigarette pants with side pockets.',
    highlights: [
      'Ready-to-Wear 3-Piece Set with Santoon Lining',
      'Intricate thread and foil lace neckline',
      'Cigarette pants with half-elasticated waistband and pockets',
    ],
    fabric: 'Chanderi Silk with Santoon Inner and Pure Organza Dupatta',
    craft: 'Precision Tailoring & Lucknowi Threadwork',
    care: 'Dry clean only.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sku: 'AAR-SAL-017',
  },
]

export function getProductBySlugOrId(slugOrId: string): CatalogProduct | null {
  if (!slugOrId) return null
  const decoded = decodeURIComponent(slugOrId).toLowerCase().trim()
  return (
    CATALOG_PRODUCTS.find(
      p => p.slug.toLowerCase() === decoded || p.id === decoded || String(p.id) === decoded,
    ) || null
  )
}

export function getRelatedProducts(currentId: string, category: string, limit = 4): CatalogProduct[] {
  const sameCategory = CATALOG_PRODUCTS.filter(
    p => p.category === category && p.id !== currentId,
  )
  if (sameCategory.length >= limit) {
    return sameCategory.slice(0, limit)
  }
  const others = CATALOG_PRODUCTS.filter(
    p => p.id !== currentId && p.category !== category,
  )
  return [...sameCategory, ...others].slice(0, limit)
}
